name: CI

on:
  pull_request:

jobs:
  build:
    name: Pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Installing dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
